// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package orderservice_cs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceCSClient is the client API for OrderServiceCS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceCSClient interface {
	AddDeliveryFeedback(ctx context.Context, in *OrderFeedbackOnDeliveryQuality, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type orderServiceCSClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceCSClient(cc grpc.ClientConnInterface) OrderServiceCSClient {
	return &orderServiceCSClient{cc}
}

func (c *orderServiceCSClient) AddDeliveryFeedback(ctx context.Context, in *OrderFeedbackOnDeliveryQuality, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/OrderServiceCS/AddDeliveryFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceCSServer is the server API for OrderServiceCS service.
// All implementations must embed UnimplementedOrderServiceCSServer
// for forward compatibility
type OrderServiceCSServer interface {
	AddDeliveryFeedback(context.Context, *OrderFeedbackOnDeliveryQuality) (*emptypb.Empty, error)
	mustEmbedUnimplementedOrderServiceCSServer()
}

// UnimplementedOrderServiceCSServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceCSServer struct {
}

func (UnimplementedOrderServiceCSServer) AddDeliveryFeedback(context.Context, *OrderFeedbackOnDeliveryQuality) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDeliveryFeedback not implemented")
}
func (UnimplementedOrderServiceCSServer) mustEmbedUnimplementedOrderServiceCSServer() {}

// UnsafeOrderServiceCSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceCSServer will
// result in compilation errors.
type UnsafeOrderServiceCSServer interface {
	mustEmbedUnimplementedOrderServiceCSServer()
}

func RegisterOrderServiceCSServer(s grpc.ServiceRegistrar, srv OrderServiceCSServer) {
	s.RegisterService(&OrderServiceCS_ServiceDesc, srv)
}

func _OrderServiceCS_AddDeliveryFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderFeedbackOnDeliveryQuality)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceCSServer).AddDeliveryFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderServiceCS/AddDeliveryFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceCSServer).AddDeliveryFeedback(ctx, req.(*OrderFeedbackOnDeliveryQuality))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderServiceCS_ServiceDesc is the grpc.ServiceDesc for OrderServiceCS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderServiceCS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OrderServiceCS",
	HandlerType: (*OrderServiceCSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDeliveryFeedback",
			Handler:    _OrderServiceCS_AddDeliveryFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order-cs.proto",
}
